In [1]:
import numpy as np

> Create a Numpy Array from a list

In [2]:
distance=[40,35,48]
speed=[8,7,24]
dis=np.array(distance)
spd=np.array(speed)
print(dis)
spd

[40 35 48]


array([ 8,  7, 24])

> Now these are precompiled numpy arrays, You can perform operations on them directly.

In [3]:
Time=dis/spd

In [4]:
Time

array([5., 5., 2.])

> You can also create Numpy array manually but To perform operations b/w two manually created array, dimensions should be same.

In [5]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50]) # same dimensions as a
print(a+b)

[11 22 33 44 55]


> To get range of numbers

In [6]:
np.arange(7,74,7)      #start,end,gap

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

> To get no. elements with same distance in a given range

In [7]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

# Dimensions in Array

> Generally we have one dimensional array, we can change it's dimensions using numpy.reshape() function

In [8]:
oneDList=[10,45,243,53,56,357,87,46,33,733,89,44,24,24,25,75,86,2344,24,345,65,97,97,76,97,87,97]
#len(oneDList)
oneDArray=np.array(oneDList)
oneDArray

array([  10,   45,  243,   53,   56,  357,   87,   46,   33,  733,   89,
         44,   24,   24,   25,   75,   86, 2344,   24,  345,   65,   97,
         97,   76,   97,   87,   97])

In [9]:
twoDArray=oneDArray.reshape(3,9)   #2 Dimension
twoDArray

array([[  10,   45,  243,   53,   56,  357,   87,   46,   33],
       [ 733,   89,   44,   24,   24,   25,   75,   86, 2344],
       [  24,  345,   65,   97,   97,   76,   97,   87,   97]])

In [10]:
oneDArray.reshape(3,3,3)   #3 Dimension

array([[[  10,   45,  243],
        [  53,   56,  357],
        [  87,   46,   33]],

       [[ 733,   89,   44],
        [  24,   24,   25],
        [  75,   86, 2344]],

       [[  24,  345,   65],
        [  97,   97,   76],
        [  97,   87,   97]]])

To convert any multidimensional array to oneD array

In [11]:
from2DArrayTo1DArray=twoDArray.ravel()  #ravel() function
from2DArrayTo1DArray.shape

(27,)

> Filter Elements of an Array

In [12]:
divisibleBy3=oneDArray%3==0
divisibleBy3

array([False,  True,  True, False, False,  True,  True, False,  True,
       False, False, False,  True,  True, False,  True, False, False,
        True,  True, False, False, False, False, False,  True, False])

In [13]:
oneDArray[divisibleBy3]

array([ 45, 243, 357,  87,  33,  24,  24,  75,  24, 345,  87])

> Array of 0 or 1

In [14]:
zeroArray=np.zeros((4,5))
zeroArray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeroArray=np.zeros((4,5))+6
zeroArray

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [16]:
oneArray=np.ones((2,4,2))
oneArray

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

> To create an Identity Matrix

In [17]:
np.eye(3) # 3X3 identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

> You can add custom element at the diagonal of array

In [18]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

To know the dimensions of any numpy array

In [19]:
twoDArray.ndim

2

In [20]:
oneDArray.ndim

1

To know total number of elements in numpy array

In [21]:
oneDArray.size

27

In [22]:
twoDArray.size

27

To know datatype of numpy array

In [23]:
twoDArray.dtype

dtype('int32')

# Some other functions

In [24]:
a.min()

1

In [25]:
a.max()

5

In [26]:
a.sum()

15

In [27]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [28]:
twoDArray.sum()  # Will sum vertical elements

5359

In [29]:
twoDArray.sum(axis=1)  # Will sum horizontal elements

array([ 930, 3444,  985])

Multiplication of two Matrices

In [30]:
twoDArr1=np.array([[1,2],[3,4]])
twoDArr2=np.array([[4,8],[9,2]])

In [31]:
twoDArr1.dot(twoDArr2)

array([[22, 12],
       [48, 32]])